version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8.10
    working_directory: ~/singnet/platform-contracts
    steps:
    - checkout
    - run:
        name: Install
        command: |
          npm install ganache-cli
          npm install
    - run:
        name: Test
        command: |
          npm run test
